export const SET_ALL_NEWS_START = 'SET_ALL_NEWS_START'
export const SET_ALL_NEWS_SUCCESS = 'SET_ALL_NEWS_SUCCESS'

export const LOAD_NEWS_START = 'LOAD_NEWS_START'
export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS'
export const LOAD_NEWS_FAILED = 'LOAD_NEWS_FAILED'

export const SEARCH_NEWS_START = 'SEARCH_NEWS_START'
export const SEARCH_NEWS_SUCCESS = 'SEARCH_NEWS_SUCCESS'
export const SEARCH_NEWS_FAILED = 'SEARCH_NEWS_FAILED'

export const LOAD_ARTICLE_START = 'LOAD_ARTICLE_START'
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS'